### ISSUE TITLE
missing getUser method missing 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/payments#23]
@hubert_krzysztofiak  jedna uwaga, bo tak patrzę teraz na te eventy nowe np. w paymentach - wszelkie klasy Event które mają być obsługiwalne przez Notifications i Templates muszą mieć metodę getUser(), a do tych w Paymentach tej metody nie dodałeś

_Issue created from a [Mattermost message](https://mattermost.etd24.pl/_redirect/pl/ntdamgjqqiy5drea8as61dqyha) *by @pa-cholek*._

**Comment by HerbertIV** [comment]
#23 close
